export const GET_BOARDS = 'GET_BOARD'
export const CREATE_BOARD = 'CREATE_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'
export const MUTATE_BOARD = 'MUTATE_BOARD'
export const IS_LOADING = 'IS_LOADING'
export const CLEAR_SETLIST = 'CLEAR_SETLIST'

export const SET_SETLIST_ERRORS = 'SET_SETLIST_ERRORS'
