export const USERS_INPUT = 'USERS_INPUT'
export const GET_USERS = 'GET_USERS'
export const SEARCH_USERS = 'SEARCH_USERS'
export const IS_USERS_LOADING = 'IS_USERS_LOADING'
export const USERS_ERROR = 'USERS_ERROR'
