export const SET_BOARD = 'SET_BOARD'
export const CREATE_BOARD = 'CREATE_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'
export const MUTATE_BOARD = 'MUTATE_BOARD'
export const IS_LOADING = 'IS_LOADING'
